language: php

php:
  - '5.4'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - DB=mysql

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi

# Script, failures in this section will result in build status 'failed'
script: "phpunit -c tests/phpunit.xml.dist"